### PR TITLE
[pkg-upd] 5.10.48-1

### PR DESCRIPTION
**Pull request by mmcrockett**

### CODE REVIEW

**Comment by trustin** [comment]
I cherry-picked from the upstream this time. Thanks for the PR, @mmcrockett :bow:

**Comment by mmcrockett** [comment]
@trustin Sorry to bother you but the sha doesn't seem to match for the `config` - was curious if you mean to change the sha or forgot to update the config file?

I tried to find how you might see config history from upstream - using the `asp checkout linux` but was lost after that :)

**Comment by trustin** [comment]
@mmcrockett I realized that when I tried to build it by myself and fixed it in 109cea1eb2253bc6969f8ddb7204554a97866d31 and 3cb57b2788339eaa53dcc1cbad85e8e86e076b11.

**Comment by trustin** [comment]
Please feel free to let me know if you still see a build problem.

**Pull request closed without merging**
